"""sua_mensagem

Revision ID: 76da55f5acd5
Revises: ef1d489cc568
Create Date: 2026-03-12 00:53:18.753601
"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa  # type: ignore
from sqlmodel import SQLModel  # type: ignore

# revision identifiers, used by Alembic.
revision: str = '76da55f5acd5'
down_revision: Union[str, Sequence[str], None] = 'ef1d489cc568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
